const subjects = [
    "Engineering Mathematics I",
    "Computer Programming",
    "Engineering Drawing I",
    "Engineering Physics",
    "Applied Mechanics",
    "Basic Electrical Engineering",

    "Engineering Mathematics II",
    "Engineering Drawing II",
    "Basic Electronics Engineering",
    "Engineering Chemistry",
    "Thermodynamics and heat Transfer",
    "Workshop Technology",

    "Engineering Mathematics III",
    "Object Oriented Programming",
    "Theory of Computation",
    "Electric Circuit Theory",
    "Electronic Devices and Circuits",
    "Digital Logic",
    "Electromagnetics",

    "Applied Mathematics",
    "Numerical Methods",
    "Instrumentation I",
    "Electrical Machines",
    "Discrete Structure",
    "Data Structure and Algorithm",
    "Microprocessor",

    "Communication English II",
    "Probability & Statistics",
    "Software Engineering",
    "Data Communication",
    "Computer Organization & Architecture",
    
    "Instrumentation II",
    "Computer Graphics",

    "Engineering Economics",
    "Object Oriented Analysis & Design",
    "Database Management System",
    "Artificial Intelligence",
    "Embedded System",
    "Operating System",
    "Minor Project",

    "Organization and Management",
    "Energy Environment and Society",
    "Project Management",
    "Computer Network",
    "Distributed System",
    "Digital Signal Analysis and Processing",
    "Elective I",

    "Project(Part A)",
    "Professional Practice",
    "Information Systems",
    "Simulation and Modelling",
    "Internet and Intranet",
    "Elective II",
    "Elective III",
    "Project(Part B)",
];

const courseCode = [
    "SH401",
    "CT401",
    "ME401",
    "SH402",
    "CE401",
    "EE401",
  
    "SH451",
    "ME451",
    "EX451",
    "SH453",
    "ME452",
    "ME453",
  
    "SH501",
    "CT501",
    "CT502",
    "EE501",
    "EX501",
    "EX502",
    "EX503",
  
    "SH551",
    "SH553",
    "EE552",
    "EE554",
    "CT551",
    "CT552",
    "EX551",
  
    "SH601",
    "SH602",
    "CT601",
    "CT602",
    "CT603",
    "EX602",
    "EX603",
  
    "CE655",
    "CT651",
    "CT652",
    "CT653",
    "CT655",
    "CT656",
    "CT654",
  
    "ME708",
    "EX701",
    "CT701",
    "CT702",
    "CT703",
    "CT704",
    "CT725",
    "CT707",
  
    "CE752",
    "CT751",
    "CT753",
    "CT754",
    "CT765",
    "CT785",
    "CT755",
];

module.exports = {subjects,courseCode};